#
# GitLeaks Repo Specific Configuration
#
# This allowlist is used to help Red Hat ignore false positives during its code scans.
#

[allowlist]
  paths = [
    '''README.md''',
    '''chart/airflow/templates/secrets.yaml''',
  ]
